### ISSUE TITLE
link to data

### ISSUE THREAD

**Issue by mattobrien415** [ashutoshraj/DynamicUnet#1]
Downloading the data from the link in the Readme gives us: 

- metadata.csv
- sample_submission.csv
- train_masks.csv
- 29bb3ece3180_11.jpg
- test.zip
- test_hq.zip
- train.zip
- train_hq.zip
- train_masks.zip

This doesn't seem consistent with the code (which wants a "codes.txt" file, etc)

**Comment by ashutoshraj** [comment]
codes.txt

car
background
